### PR TITLE
Run scapy on various architectures

### PR DESCRIPTION
**Pull request by evverx**
prompted by https://github.com/secdev/scapy/issues/3847

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
Hi @evverx, Packit project lead here..;)

I've randomly discovered your pull request and I must say you've found a really interesting way how to run tests via Packit!

If you want, there is also a separate `test` job that can be used instead:
* https://packit.dev/docs/testing-farm/
* The tests use FMF format as their definition, but looking at the examples, I hope you can make it work easily. (As a benefit, the very same definition can be used in Fedora distribution git.)
* By default, tests run after the RPM build but you can use `skip_build` option to run tests without any build.
* Here are currently available composes you can use: https://api.dev.testing-farm.io/v0.1/composes ..Aha. OK, now I see that you are interested in various other architectures... Aren't you? Let me ask Testing Farm maintainers what we can do about that.

As a side note, Packit [can help you with the Fedora releases as well](https://packit.dev/docs/fedora-releases-guide/).

Let [me/us know](https://packit.dev/#contact) if you need any help and have a nice day!

**Comment by lachmanfrantisek** [comment]
Ok, so it looks like more architectures will not come into the Testing Farm (the test runner we use) soon. Here is a relevant page of theirs: https://docs.testing-farm.io/general/0.1/test-environment.html#_supported_architectures

**Comment by evverx** [comment]
Hi @lachmanfrantisek!

> I must say you've found a really interesting way how to run tests via Packit!

I'm glad you found it interesting :-) but credit where credit's due, as far as I can remember this technique was invented by @mrc0mmand and I just borrowed the idea. I think it's kind of perfect in terms of bringing Packit to upstream projects because it doesn't bring a lot of rpm-specific stuff apart from just one config that can be easily edited if/when specfiles change. Other than that it's the only way to build projects on big-endian and 32-bit machines.

>  now I see that you are interested in various other architectures

In this particular case the most interesting architecture was s390x because due to its endianness bugs like https://github.com/secdev/scapy/pull/3883 surface only there.

> Let [me/us know](https://packit.dev/#contact) if you need any help and have a nice day!

Thanks! I think it would be great to hook up the main `scapy` repository eventually to Packit because it would make it easier to spot issues where for example `pack`s and `unpack`s in dissectors don't match or where byte order isn't specified explicitly but that hasn't been discussed upstream yet.

**Comment by evverx** [comment]
Packit was integrated upstream in https://github.com/secdev/scapy/pull/4355 with `manual_trigger` on top (https://github.com/secdev/scapy/pull/4356). Closing it here.

I'm not sure how to get Packit to merge PRs with the master branch before the tests are run though (https://packit.dev/docs/configuration#merge_pr_in_ci doesn't seem to work) but it could be that I'm missing something.

**Comment by lachmanfrantisek** [comment]
Hi @evverx , the merging should be done automatically by default. Do you have an example where you are not sure this worked as expected?

**Comment by evverx** [comment]
@lachmanfrantisek as far as I can remember I noticed it in https://github.com/systemd/systemd/pull/22191#issuecomment-1018888351 back in 2022 and have seen it several times since then. I'm not sure if I still have recent build logs where I thought it didn't work. I'll report it if I notice it again.

**Pull request closed without merging**
